### ISSUE TITLE
Getting a official twrp for mi 9 se?

### ISSUE THREAD

**Issue by jasle** [mauronofrio/android_device_xiaomi_grus#1]
Is there any blocking issue on this, to get it a offical lineage image?

What need to be done, to get it a offical image?

**Comment by mauronofrio** [comment]
It needs a bit of work, if you can test i will send you a twrp

**Comment by jasle** [comment]
oh, sorry, mixed up lineage os and twrp in the issue 🙈. Looking for an offical twrp-image of course.

I have a mi 9 se 128GB global version and can test twrp on it. If i have some time, I could also build the image from the repo myself.

Have you any special tasks to test or to look at?

**Comment by mauronofrio** [comment]
In all cases actually i'm not supporting the twrp for grus, i saw there are others devs that are working on it, ask them to make the twrp official.
